### ISSUE TITLE
dicom2nifti conversion with dicom2nifti-2.2.12 and python3.8.0

### ISSUE THREAD

**Issue by FredTestud** [icometrix/dicom2nifti#92]
Dear icometrix team,
I want to report the following bug. 

I want to convert a dicom series to nifti.  I am using ubuntu 18.04 LTS installed in win10. 
When using Python 3.8.0, dicom2nifti-2.2.12 and I get the error
 AttributeError: 'Dataset' object has no attribute 'fileobj_type' 

Here the 
>>> import pydicom
>>> import dicom2nifti
>>> outdir= '/mnt/c/Temp/PHANTOM_TT/'
>>> dir= '/mnt/c/Temp/PHANTOM_TT/MRAC_BRAIN_HIRES_IN_0003'
>>> dicom2nifti.dicom_series_to_nifti(dir, '%s/opposedphase1.nii.gz' % outdir, reorient_nifti=True)
Traceback (most recent call last):
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/dicom2nifti/convert_dicom.py", line 84, in dicom_series_to_nifti
    dicom_input = common.read_dicom_directory(dicom_directory)
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/dicom2nifti/common.py", line 48, in read_dicom_directory
    dicom_headers = compressed_dicom.read_file(file_path,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/dicom2nifti/compressed_dicom.py", line 15, in read_file
    if _is_compressed(dicom_file, force):
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/dicom2nifti/compressed_dicom.py", line 104, in _is_compressed
    header = pydicom.read_file(dicom_file,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/filereader.py", line 879, in dcmread
    dataset = read_partial(fp, stop_when, defer_size=defer_size,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/filereader.py", line 770, in read_partial
    new_dataset = dataset_class(fileobj, dataset, preamble, file_meta_dataset,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/dataset.py", line 1364, in __init__
    Dataset.__init__(self, dataset)
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/dataset.py", line 177, in __init__
    dict.__init__(self, *args)
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/dataset.py", line 597, in __getitem__
    self.fileobj_type, self.filename, self.timestamp,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/dataset.py", line 520, in __getattr__
    return super(Dataset, self).__getattribute__(name)
AttributeError: 'Dataset' object has no attribute 'fileobj_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/dicom2nifti/convert_dicom.py", line 89, in dicom_series_to_nifti
    reraise(
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/dicom2nifti/convert_dicom.py", line 84, in dicom_series_to_nifti
    dicom_input = common.read_dicom_directory(dicom_directory)
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/dicom2nifti/common.py", line 48, in read_dicom_directory
    dicom_headers = compressed_dicom.read_file(file_path,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/dicom2nifti/compressed_dicom.py", line 15, in read_file
    if _is_compressed(dicom_file, force):
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/dicom2nifti/compressed_dicom.py", line 104, in _is_compressed
    header = pydicom.read_file(dicom_file,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/filereader.py", line 879, in dcmread
    dataset = read_partial(fp, stop_when, defer_size=defer_size,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/filereader.py", line 770, in read_partial
    new_dataset = dataset_class(fileobj, dataset, preamble, file_meta_dataset,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/dataset.py", line 1364, in __init__
    Dataset.__init__(self, dataset)
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/dataset.py", line 177, in __init__
    dict.__init__(self, *args)
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/dataset.py", line 597, in __getitem__
    self.fileobj_type, self.filename, self.timestamp,
  File "/home/z003fsynu/.local/lib/python3.8/site-packages/pydicom/dataset.py", line 520, in __getattr__
    return super(Dataset, self).__getattribute__(name)
dicom2nifti.exceptions.ConversionError: 'Dataset' object has no attribute 'fileobj_type'

The conversion works with python2.7.17 and dicom2nifti-2.2.12. 

Is there a work around, until this bug is fixed? 

This has been tested with not anonymized phantom DCMs (MRI).

Thank you for your help.

Best regards

Frederik

**Comment by FredTestud** [comment]
It looks like it was version 2.1.9 was installed and not updated.
I close this issue for now. 

Best regards

Frederik
