### ISSUE TITLE
AttributeError: 'Dataset' object has no attribute 'fileobj_type'

### ISSUE THREAD

**Issue by burns101** [icometrix/dicom2nifti#44]
get the error "AttributeError: 'Dataset' object has no attribute 'fileobj_type'" when trying to work with a dicom data set. I am perfectly able to open the dataset using pydicom and extracting the array and header infor using for loops.

dataset included

edit: using python 3.7 and dicom2nifti 2.0.5

code bellow:

`import dicom2nifti
a = r'C:\Users\User\Google Drive\Dissertation\Work\Subjects\sub_01'
b = r'C:\Users\User\Google Drive\Dissertation\Work'
dicom2nifti.convert_directory(a, b)`

error message:

"Unable to read: C:\Users\User\Google Drive\Dissertation\Work\Subjects\sub_01\EXP180105_LYR_SCAN14.MR.SYTSAI_BRAIN.0003.0001.2018.01.05.11.29.40.942370.31044194.IMA
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dicom2nifti\convert_dir.py", line 57, in convert_directory
    force=dicom2nifti.settings.pydicom_read_force)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dicom2nifti\compressed_dicom.py", line 15, in read_file
    if _is_compressed(dicom_file, force):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dicom2nifti\compressed_dicom.py", line 107, in _is_compressed
    force=force)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pydicom\filereader.py", line 880, in dcmread
    force=force, specific_tags=specific_tags)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pydicom\filereader.py", line 771, in read_partial
    is_implicit_VR, is_little_endian)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pydicom\dataset.py", line 1364, in __init__
    Dataset.__init__(self, dataset)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pydicom\dataset.py", line 177, in __init__
    dict.__init__(self, *args)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pydicom\dataset.py", line 597, in __getitem__
    self.fileobj_type, self.filename, self.timestamp,
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pydicom\dataset.py", line 520, in __getattr__
    return super(Dataset, self).__getattribute__(name)
AttributeError: 'Dataset' object has no attribute 'fileobj_type'
Unable to read: C:\Users\User\Google Drive\Dissertation\Work\Subjects\sub_01\EXP180105_LYR_SCAN14.MR.SYTSAI_BRAIN.0003.0002.2018.01.05.11.29.40.942370.31044212.IMA"

[sub_01.zip](https://github.com/icometrix/dicom2nifti/files/2533538/sub_01.zip)

![capture1](https://user-images.githubusercontent.com/33559440/47777655-2abd0700-dd30-11e8-91cf-7decb368984f.PNG)

**Comment by abrys** [comment]
Can you provide full version info for the following
- python (i see 3.7 which is not tested however would not expect any issues)
- dicom2nifti
- pydicom

We cannot reproduce the issue however we do not test with windows and python 3.7.
Where you able to use it before or is this the first time testing it?

[3_mprage_sag_1mm_iso_g2.nii.gz](https://github.com/icometrix/dicom2nifti/files/2533596/3_mprage_sag_1mm_iso_g2.nii.gz)

**Comment by burns101** [comment]
works perfectly on python 3.5!

**Comment by abrys** [comment]
During some testing of other stuff I was able to reproduce this issue.
It seems like the newer pydicom does not like specifying defer_size as an integer but in string format.
The downside is that it seems that the minimum is "1 KB"
Fixing the issue this way.

**Comment by abrys** [comment]
Will be fixed in 2.0.8
